name: Clear Releases with GH CLI

on:
  workflow_dispatch:

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete all releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          gh release list | awk '{print $1}' | xargs -I {} gh release delete --yes {}
          echo "All releases deleted"