name: Clear Releases with GH CLI

on:
  workflow_dispatch:

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete all releases
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt
          rm token.txt
          
          gh release list | awk '{print $1}' | xargs -I {} gh release delete --yes {}
          echo "All releases deleted"